### ISSUE TITLE
Any chance to upgrade python image to 3.11?

### ISSUE THREAD

**Issue by sdelquin** [nelsonjchen/gh-pages-pelican-action#13]
https://github.com/nelsonjchen/gh-pages-pelican-action/blob/master/Dockerfile#L1

**Comment by nelsonjchen** [comment]
Sure, send a PR in. I don't really maintain this action though.

**Comment by gerrowadat** [comment]
Have added https://github.com/nelsonjchen/gh-pages-pelican-action/pull/15 which will bump to 3.12 (that's even one more than eleven!).
