### ISSUE TITLE
Please show a demo for me

### ISSUE THREAD

**Issue by tengshan2008** [nelsonjchen/gh-pages-pelican-action#4]
I made this action for my  github page, but I get this:

```
=================== Install Requirements ===================
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
##[error]Docker run failed with exit code 1
```

please show a demo for me.

PS: I have a requirements.txt in my source branch.

**Comment by nelsonjchen** [comment]
https://github.com/tengshan2008/tengshan2008.github.io/pull/4

**Comment by nelsonjchen** [comment]
😅 you have to checkout the repo before running actions.

**Comment by nelsonjchen** [comment]
Oof, you're now hitting the SSH key thing. GitHub fixed this. Anyway, I'll reopen this. There really should be a demo anyway.

**Comment by tengshan2008** [comment]
Thanks for you answer, what can I do?

**Comment by tengshan2008** [comment]
Anthor question, How to use `PELICAN_CONFIG_FILE` ?

**Comment by nelsonjchen** [comment]
If you look at the code, you can give it the path to the `pelicanconf.py` file.
